### ISSUE TITLE
prefix option

### ISSUE THREAD

**Issue by jongacnik** [jongacnik/gr8-util#3]
Add a `prefix` option for namespacing rules. This become really useful with the new hoverstate (`pseudo`) option. These are font-color hover utilities namespaced by a `.no-touch` class:

```js
var css = util({
  prop: { fc: 'color' },
  vals: [
    'red',
    'blue',
    'green'
  ],
  pseudo: 'hover',
  prefix: '.no-touch '
})
```

```css
.no-touch .fcr-h:hover{color:red}
.no-touch .fcb-h:hover{color:blue}
.no-touch .fcg-h:hover{color:green}
```

When I do this change I also want to change `tail` to `suffix` for consistency (I will leave an alias for `tail` so it does not break).
